# Generated by Django 5.0 on 2024-03-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_date_issued_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('shipped', 'Shipping'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processed', max_length=50),
        ),
    ]
