# Generated by Django 5.0 on 2024-03-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_address_line_2_order_building_villa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building_villa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
