# Generated by Django 5.0 on 2024-02-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_zipcode_userprofile_postal_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='postal_zip_code',
            new_name='zipcode',
        ),
    ]
