# Generated by Django 5.0 on 2024-03-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_postal_zip_code_userprofile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
