# Generated by Django 5.0 on 2024-03-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_1',
            new_name='building_villa',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_2',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='state_province_region',
            new_name='street',
        ),
    ]
