# Generated by Django 5.0 on 2024-02-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_date_created_alter_product_photo'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhisListItem',
            new_name='WishListItem',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='wislist',
            new_name='wishlist',
        ),
    ]
